"""setup vacancy

Revision ID: 919d2df7f11c
Revises: ba3dd98a2366
Create Date: 2024-06-06 19:08:39.559797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '919d2df7f11c'
down_revision: Union[str, None] = 'ba3dd98a2366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.Column('hh_id', sa.Integer(), nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('salary_from', sa.Integer(), nullable=True),
                    sa.Column('salary_to', sa.Integer(), nullable=True),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('is_remote', sa.Boolean(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('team', sa.String(), nullable=False),
                    sa.Column('todo', sa.String(), nullable=False),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('employment_type_id', sa.String(), nullable=True),
                    sa.Column('division_id', sa.String(), nullable=True),
                    sa.Column('qualification_id', sa.String(), nullable=True),
                    sa.Column('skills', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('owner_id', sa.String(), nullable=True),
                    sa.Column('company_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    # ### end Alembic commands ###
