"""reply add chat id

Revision ID: a63dabd6320f
Revises: 9bf39bf32f89
Create Date: 2024-06-16 11:43:02.839300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63dabd6320f'
down_revision: Union[str, None] = '9bf39bf32f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'chat_id')
    # ### end Alembic commands ###
