"""name vacancy

Revision ID: 32ecd20cdf03
Revises: 7fd52c7442e7
Create Date: 2024-06-08 14:35:45.521490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ecd20cdf03'
down_revision: Union[str, None] = '7fd52c7442e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
