"""comment user reply

Revision ID: 1fc9b9bbfa25
Revises: c9f85cbed00d
Create Date: 2024-06-15 12:36:16.123386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc9b9bbfa25'
down_revision: Union[str, None] = 'c9f85cbed00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('user_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'user_comment')
    # ### end Alembic commands ###
