"""dump vacancy name to reply

Revision ID: c9f85cbed00d
Revises: eb4cbcbd26cf
Create Date: 2024-06-14 19:34:42.302959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f85cbed00d'
down_revision: Union[str, None] = 'eb4cbcbd26cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('vacancy_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'vacancy_name')
    # ### end Alembic commands ###
