"""group to skills

Revision ID: 6fea0d8c669f
Revises: ca7b9f7b1f41
Create Date: 2024-06-12 17:49:25.087936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fea0d8c669f'
down_revision: Union[str, None] = 'ca7b9f7b1f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_skill', sa.Column('group', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
