"""add reply reason

Revision ID: 17b54373c550
Revises: 6fea0d8c669f
Create Date: 2024-06-13 11:27:24.515466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b54373c550'
down_revision: Union[str, None] = '6fea0d8c669f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'reason')
    # ### end Alembic commands ###
