"""init replies

Revision ID: f452c1e77f74
Revises: 32ecd20cdf03
Create Date: 2024-06-08 17:17:48.911205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f452c1e77f74'
down_revision: Union[str, None] = '32ecd20cdf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vacancy_id', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=True),
    sa.Column('applicant_avatar', sa.String(), nullable=True),
    sa.Column('applicant_fullname', sa.String(), nullable=True),
    sa.Column('applicant_phone', sa.String(), nullable=True),
    sa.Column('applicant_telegram', sa.String(), nullable=True),
    sa.Column('applicant_email', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('reply_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
