"""update reply field rules

Revision ID: ca7b9f7b1f41
Revises: 013a8e148111
Create Date: 2024-06-12 15:40:08.698790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ca7b9f7b1f41'
down_revision: Union[str, None] = '013a8e148111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('updated_by_role', sa.String(), nullable=True))
    op.alter_column('replies', 'owner_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
