"""add relationship between user and applicant

Revision ID: b562d22d8dcf
Revises: a075af452232
Create Date: 2024-06-11 18:06:36.487012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b562d22d8dcf'
down_revision: Union[str, None] = 'a075af452232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE applicants ALTER COLUMN user_id TYPE uuid USING user_id::uuid")
    op.create_foreign_key(None, 'applicants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
