"""add relationship applicant to education

Revision ID: eb4cbcbd26cf
Revises: e367e69b6a66
Create Date: 2024-06-13 16:07:23.125417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4cbcbd26cf'
down_revision: Union[str, None] = 'e367e69b6a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'applicant_education', 'applicants', ['applicant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
