"""vacancy with dict

Revision ID: 3f1c801876e3
Revises: 
Create Date: 2024-06-07 13:49:52.914484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3f1c801876e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_city',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('fias_id', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.Column('habr_alias', sa.String(length=50), nullable=True),
                    sa.Column('country_name', sa.String(length=50), nullable=True),
                    sa.Column('region_name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_division',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_employment_type',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.String(length=50), nullable=True),
                    sa.Column('hh_id', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_qualification',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vacancies',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.Column('hh_id', sa.Integer(), nullable=True),
                    sa.Column('url', sa.String(), nullable=True),
                    sa.Column('salary_from', sa.Integer(), nullable=True),
                    sa.Column('salary_to', sa.Integer(), nullable=True),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('is_remote', sa.Boolean(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('team', sa.String(), nullable=False),
                    sa.Column('todo', sa.String(), nullable=False),
                    sa.Column('city_id', sa.String(), nullable=True),
                    sa.Column('employment_type_id', sa.String(), nullable=True),
                    sa.Column('division_id', sa.String(), nullable=True),
                    sa.Column('qualification_id', sa.String(), nullable=True),
                    sa.Column('skills', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('owner_id', sa.String(), nullable=True),
                    sa.Column('company_id', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies')
    op.drop_table('dict_qualification')
    op.drop_table('dict_employment_type')
    op.drop_table('dict_division')
    op.drop_table('dict_city')
    # ### end Alembic commands ###
