"""setup vacancy with dicts

Revision ID: ba3dd98a2366
Revises: 
Create Date: 2024-06-06 18:31:30.564877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ba3dd98a2366'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_city',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('fias_id', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.Column('habr_alias', sa.String(length=50), nullable=True),
                    sa.Column('country_name', sa.String(length=50), nullable=True),
                    sa.Column('region_name', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_division',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_employment_type',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('habr_id', sa.String(length=50), nullable=True),
                    sa.Column('hh_id', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dict_qualification',
                    sa.Column('id', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('habr_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dict_qualification')
    op.drop_table('dict_employment_type')
    op.drop_table('dict_division')
    op.drop_table('dict_city')
    # ### end Alembic commands ###
