"""add relationship applicant to xp

Revision ID: e367e69b6a66
Revises: 17b54373c550
Create Date: 2024-06-13 15:37:11.479977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e367e69b6a66'
down_revision: Union[str, None] = '17b54373c550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'applicant_xp', 'applicants', ['applicant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
