"""add applicant education

Revision ID: 013a8e148111
Revises: b562d22d8dcf
Create Date: 2024-06-12 12:56:04.329125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '013a8e148111'
down_revision: Union[str, None] = 'b562d22d8dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'applicant_education',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('applicant_id', sa.String(length=50), nullable=False),
        sa.Column('university_name', sa.String(), nullable=False),
        sa.Column('university_id', sa.String(), nullable=True),
        sa.Column('faculty_name', sa.String(), nullable=False),
        sa.Column('faculty_id', sa.String(), nullable=True),
        sa.Column('city_id', sa.String(length=50), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('specialization', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('applicants', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
