"""fix nullable in reply

Revision ID: c12d45f876a7
Revises: f452c1e77f74
Create Date: 2024-06-08 18:03:01.754088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12d45f876a7'
down_revision: Union[str, None] = 'f452c1e77f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
