services:
  api:
    build:
      context: .
    container_name: skillometer-api
    image: ilyamachetto/skillometer-api:0.2.1
    platform: linux/amd64
    env_file:
      - .env.development
    ports:
      - "80:8080"