services:
  api:
    build:
      context: .
      args:
        DOCKER_TAG: ${TAG}
    container_name: skillometer-api
    image: ilyamachetto/skillometer-api:${TAG}
    platform: linux/amd64
    env_file:
      - .env.development
    ports:
      - "80:8080"