[tool.poetry]
name = "skillometer-api"
version = "1.0.0"
description = ""
authors = ["Ilya Zhuravlev <ichirozcom@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
