apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: skillometer
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ilyamachetto/skillometer-api:0.1.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DOMAIN
              value: "skillometer.idev-present.com"
            - name: ENVIRONMENT
              value: "staging"
            - name: API_PREFIX
              value: "/api/v1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_DIR
              value: "/var/log/"
            - name: DATABASE_SERVER
              value: "postgres-postgresql.skillometer.svc.cluster.local"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "skillometer_dba"
            - name: DATABASE_PASSWORD
              value: "skillometer_dba_idev2512"
            - name: DATABASE_DBNAME
              value: "skillometer_db"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: skillometer
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080