apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: skillometer
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ilyamachetto/skillometer-api:0.10.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DOMAIN
              value: "skillometer.idev-present.com"
            - name: ENVIRONMENT
              value: "staging"
            # APi config
            - name: API_PREFIX
              value: "/api/v1"
            - name: SECRET_KEY
              value: "1e25d4c7adb24858659ba325ba332417c69392909875c4225114489fbf41d122"
            - name: CORS_ORIGINS
              value: "http://localhost,http://localhost:8080,https://localhost:9000,https://localhost:8000,http://localtest.me,https://skillometer.idev-present.com,https://admin.skillometer.idev-present.com"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_DIR
              value: "/var/log/"
            - name: FS_TYPE
              value: "SBER"
            # Database
            - name: DATABASE_SERVER
              value: "10.244.0.204"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "skillometer_dba"
            - name: DATABASE_PASSWORD
              value: "skillometer_dba_idev2512"
            - name: DATABASE_DBNAME
              value: "skillometer_db"
            # IAM
            - name: IAM_HOSTNAME
              value: "http://10.244.0.227:8000"
            - name: IAM_CLIENT_ID
              value: "8aa124a89a76caf4e84b"
            - name: IAM_CLIENT_SECRET
              value: "fa026ac3608de86085c8fe9cbac8f784ba764fd1"
            - name: IAM_REDIRECT_URI
              value: "https://skillometer.idev-present.com/api/v1/user/auth/callback"
            - name: IAM_ORGANIZATION_ID
              value: "skillometer"
            - name: IAM_APPLICATION_ID
              value: "skillometer"
            # S3
            - name: S3_ENDPOINT
              value: "https://s3.cloud.ru"
            - name: S3_API_KEY
              value: "c90b7ab7cb7a0c774be72124413d910b"
            - name: S3_SECRET_KEY
              value: "5ef1e5a7209a701035d18343a064a43f"
            - name: S3_TENANT_ID
              value: "d380f324-2845-4fac-8afb-398bb612359f"
            - name: S3_BUCKET_NAME
              value: "resume"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: skillometer
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080