GET https://career.habr.com/api/v1/integrations/specializations?access_token=RnRjMXRwSk9DN3dUek1FMDlCR2F3ZU5FaG9UK1cyU0Fkb0dqNzJWMkFudWZmUC9PZmdCWXhPKzBRY0V6aUdKcG82TWJRVE9BaXd1K2I4WHBPMkFHL3ZWWjBJdUd6MzhBdDBNS1V2UXBVdUhjaXFWV1g2NlJ5TGIwWXY3TFY2VEo2UUVPeXdkV3NYZ2pPRmhWVmM4TDc4dnR6RUN5dWFEd2ZUS0g0ZGFBNTExVlA5amtYTlBnSENNRG9SRURJMjhNL1kyWmZFUEpiMUpNKzhYWnFtTktmYjJoSmxWd2tNMFhHMldEN21ta3VrbDJmT0lNK1pBR0VySHdxV3BDcWR0YS0tOWJybytiZVR6WXVjQXRmNDRtbGkrZz09--8da36670eeb624951c3ae57787893c640e50d01e